apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: remove-headers-lua-filter-1-3
spec:
  filters:
  - listenerMatch:
      listenerType: GATEWAY
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |-
          headersToCheck = {{ .Values.headersToCheck }}
{{ .Files.Get "script.lua" | nindent 10 }}
